EXIT_SUCCESS: int = 0
EXIT_NEEDS_HUMAN: int = 10
EXIT_JUDGE_REJECTED: int = 20
EXIT_PARTIAL_FAILURE: int = 30
EXIT_CONFIG_ERROR: int = 40
EXIT_GIT_ERROR: int = 50
EXIT_LLM_ERROR: int = 60
EXIT_UNKNOWN_ERROR: int = 1
